linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - revive
    - gosec
    - bodyclose
    - sqlclosecheck
    - noctx
    - errorlint
    - contextcheck
run:
  timeout: 5m
issues:
  exclude-use-default: false
